<?xml version="1.0"?>
<package format="3">
  <name>path_searching</name>
  <version>0.0.0</version>
  <description>The path_searching package (ROS2)</description>

  <maintainer email="bzhouai@todo.todo">bzhouai</maintainer>
  <maintainer email="rninamdar@wpi.edu">rninamdar</maintainer>
  <license>LGPL-3.0-or-later</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>eigen3_cmake_module</build_depend>
  <build_export_depend>eigen3_cmake_module</build_export_depend>
  <depend>eigen</depend>

  <depend>rclcpp</depend>
  <depend>plan_env</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
